#pragma once

#include "ember/core.h"

/**
 * @brief Describes a data format used by the ember_gpu subsystem.
 * Any other format values outside this enum is not supported by 
 * the subsystem.
 *
 * Used for vertex attributes, textures, and general GPU data.
 */
typedef enum emgpu_format {
    EMGPU_FORMAT_UNDEFINED = 0,

    /**
     * @brief 8-bit integer formats
     */
    EMGPU_FORMAT_R8_UINT    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 1, 0),
    EMGPU_FORMAT_RG8_UINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 2, 0),
    EMGPU_FORMAT_RGB8_UINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, 0),
    EMGPU_FORMAT_RGBA8_UINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, 0),

    EMGPU_FORMAT_R8_SINT    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 1, 0),
    EMGPU_FORMAT_RG8_SINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 2, 0),
    EMGPU_FORMAT_RGB8_SINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 3, 0),
    EMGPU_FORMAT_RGBA8_SINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 4, 0),

    /**
     * @brief 8-bit normalized formats
     */
    EMGPU_FORMAT_R8_UNORM    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 1, EMBER_FORMAT_FLAG_NORMALIZED),
    EMGPU_FORMAT_RG8_UNORM   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 2, EMBER_FORMAT_FLAG_NORMALIZED),
    EMGPU_FORMAT_RGB8_UNORM  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_NORMALIZED),
    EMGPU_FORMAT_RGBA8_UNORM = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_NORMALIZED),

    EMGPU_FORMAT_R8_SNORM    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 1, EMBER_FORMAT_FLAG_NORMALIZED),
    EMGPU_FORMAT_RG8_SNORM   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 2, EMBER_FORMAT_FLAG_NORMALIZED),
    EMGPU_FORMAT_RGB8_SNORM  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 3, EMBER_FORMAT_FLAG_NORMALIZED),
    EMGPU_FORMAT_RGBA8_SNORM = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 4, EMBER_FORMAT_FLAG_NORMALIZED),

    /**
     * @brief 16-bit formats
     */
    EMGPU_FORMAT_R16_UINT    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 16, 1, 0),
    EMGPU_FORMAT_RG16_UINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 16, 2, 0),
    EMGPU_FORMAT_RGB16_UINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 16, 3, 0),
    EMGPU_FORMAT_RGBA16_UINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 16, 4, 0),

    EMGPU_FORMAT_R16_SINT    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 16, 1, 0),
    EMGPU_FORMAT_RG16_SINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 16, 2, 0),
    EMGPU_FORMAT_RGB16_SINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 16, 3, 0),
    EMGPU_FORMAT_RGBA16_SINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 16, 4, 0),

    EMGPU_FORMAT_R16_FLOAT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 16, 1, 0),
    EMGPU_FORMAT_RG16_FLOAT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 16, 2, 0),
    EMGPU_FORMAT_RGB16_FLOAT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 16, 3, 0),
    EMGPU_FORMAT_RGBA16_FLOAT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 16, 4, 0),

    /**
     * @brief 32-bit formats
     */
    EMGPU_FORMAT_R32_UINT    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT,  32, 1, 0),
    EMGPU_FORMAT_RG32_UINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT,  32, 2, 0),
    EMGPU_FORMAT_RGB32_UINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT,  32, 3, 0),
    EMGPU_FORMAT_RGBA32_UINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT,  32, 4, 0),

    EMGPU_FORMAT_R32_SINT    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT,  32, 1, 0),
    EMGPU_FORMAT_RG32_SINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT,  32, 2, 0),
    EMGPU_FORMAT_RGB32_SINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT,  32, 3, 0),
    EMGPU_FORMAT_RGBA32_SINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT,  32, 4, 0),

    EMGPU_FORMAT_R32_FLOAT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 32, 1, 0),
    EMGPU_FORMAT_RG32_FLOAT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 32, 2, 0),
    EMGPU_FORMAT_RGB32_FLOAT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 32, 3, 0),
    EMGPU_FORMAT_RGBA32_FLOAT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 32, 4, 0),

    /**
     * @brief sRGB formats
     */
    EMGPU_FORMAT_R8_SRGB    = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 1, EMBER_FORMAT_FLAG_SRGB),
    EMGPU_FORMAT_RG8_SRGB   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 2, EMBER_FORMAT_FLAG_SRGB),
    EMGPU_FORMAT_RGB8_SRGB  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_SRGB),
    EMGPU_FORMAT_RGBA8_SRGB = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_SRGB),

    /**
     * @brief BGR formats
     */
    EMGPU_FORMAT_BGR8_UNORM  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGR8_SNORM  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 3, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGR8_UINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGR8_SINT   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 3, EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGR8_SRGB   = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_SRGB | EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGRA8_UNORM = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGRA8_SNORM = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 4, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGRA8_UINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGRA8_SINT  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 4, EMBER_FORMAT_FLAG_BGRA),
    EMGPU_FORMAT_BGRA8_SRGB  = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_SRGB | EMBER_FORMAT_FLAG_BGRA),
    
    /**
     * @brief Depth/stencil formats
     */
    EMGPU_FORMAT_D16_UNORM        = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 16, 1, EMBER_FORMAT_FLAG_DEPTH),
    EMGPU_FORMAT_D24_UNORM        = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 24, 1, EMBER_FORMAT_FLAG_DEPTH),
    EMGPU_FORMAT_D32_FLOAT        = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 32, 1, EMBER_FORMAT_FLAG_DEPTH),

    EMGPU_FORMAT_D24_UNORM_S8_UINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 32, 2, EMBER_FORMAT_FLAG_DEPTH | EMBER_FORMAT_FLAG_STENCIL),
    EMGPU_FORMAT_D32_FLOAT_S8_UINT = EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_FLOAT, 40, 2, EMBER_FORMAT_FLAG_DEPTH | EMBER_FORMAT_FLAG_STENCIL),
} emgpu_format;