#pragma once

#include "ember/core.h"

/**
 * @brief Code for identifying a keyboard button.
 */
typedef enum emwin_key_code {
    EMBER_KEY_SPACE              ,
    EMBER_KEY_APOSTROPHE         ,
    EMBER_KEY_COMMA              ,
    EMBER_KEY_MINUS              ,
    EMBER_KEY_PERIOD             ,
    EMBER_KEY_SLASH              ,
    EMBER_KEY_0                  ,
    EMBER_KEY_1                  ,
    EMBER_KEY_2                  ,
    EMBER_KEY_3                  ,
    EMBER_KEY_4                  ,
    EMBER_KEY_5                  ,
    EMBER_KEY_6                  ,
    EMBER_KEY_7                  ,
    EMBER_KEY_8                  ,
    EMBER_KEY_9                  ,
    EMBER_KEY_SEMICOLON          ,
    EMBER_KEY_EQUAL              ,
    EMBER_KEY_A                  ,
    EMBER_KEY_B                  ,
    EMBER_KEY_C                  ,
    EMBER_KEY_D                  ,
    EMBER_KEY_E                  ,
    EMBER_KEY_F                  ,
    EMBER_KEY_G                  ,
    EMBER_KEY_H                  ,
    EMBER_KEY_I                  ,
    EMBER_KEY_J                  ,
    EMBER_KEY_K                  ,
    EMBER_KEY_L                  ,
    EMBER_KEY_M                  ,
    EMBER_KEY_N                  ,
    EMBER_KEY_O                  ,
    EMBER_KEY_P                  ,
    EMBER_KEY_Q                  ,
    EMBER_KEY_R                  ,
    EMBER_KEY_S                  ,
    EMBER_KEY_T                  ,
    EMBER_KEY_U                  ,
    EMBER_KEY_V                  ,
    EMBER_KEY_W                  ,
    EMBER_KEY_X                  ,
    EMBER_KEY_Y                  ,
    EMBER_KEY_Z                  ,
    EMBER_KEY_LEFT_BRACKET       ,
    EMBER_KEY_BACKSLASH          ,
    EMBER_KEY_RIGHT_BRACKET      ,
    EMBER_KEY_GRAVE_ACCENT       ,
    EMBER_KEY_WORLD_1            ,
    EMBER_KEY_WORLD_2            ,
    EMBER_KEY_ESCAPE             ,
    EMBER_KEY_ENTER              ,
    EMBER_KEY_TAB                ,
    EMBER_KEY_BACKSPACE          ,
    EMBER_KEY_INSERT             ,
    EMBER_KEY_DELETE             ,
    EMBER_KEY_RIGHT              ,
    EMBER_KEY_LEFT               ,
    EMBER_KEY_DOWN               ,
    EMBER_KEY_UP                 ,
    EMBER_KEY_PAGE_UP            ,
    EMBER_KEY_PAGE_DOWN          ,
    EMBER_KEY_HOME               ,
    EMBER_KEY_END                ,
    EMBER_KEY_CAPS_LOCK          ,
    EMBER_KEY_SCROLL_LOCK        ,
    EMBER_KEY_NUM_LOCK           ,
    EMBER_KEY_PRINT_SCREEN       ,
    EMBER_KEY_PAUSE              ,
    EMBER_KEY_F1                 ,
    EMBER_KEY_F2                 ,
    EMBER_KEY_F3                 ,
    EMBER_KEY_F4                 ,
    EMBER_KEY_F5                 ,
    EMBER_KEY_F6                 ,
    EMBER_KEY_F7                 ,
    EMBER_KEY_F8                 ,
    EMBER_KEY_F9                 ,
    EMBER_KEY_F10                ,
    EMBER_KEY_F11                ,
    EMBER_KEY_F12                ,
    EMBER_KEY_F13                ,
    EMBER_KEY_F14                ,
    EMBER_KEY_F15                ,
    EMBER_KEY_F16                ,
    EMBER_KEY_F17                ,
    EMBER_KEY_F18                ,
    EMBER_KEY_F19                ,
    EMBER_KEY_F20                ,
    EMBER_KEY_F21                ,
    EMBER_KEY_F22                ,
    EMBER_KEY_F23                ,
    EMBER_KEY_F24                ,
    EMBER_KEY_F25                ,
    EMBER_KEY_KP_0               ,
    EMBER_KEY_KP_1               ,
    EMBER_KEY_KP_2               ,
    EMBER_KEY_KP_3               ,
    EMBER_KEY_KP_4               ,
    EMBER_KEY_KP_5               ,
    EMBER_KEY_KP_6               ,
    EMBER_KEY_KP_7               ,
    EMBER_KEY_KP_8               ,
    EMBER_KEY_KP_9               ,
    EMBER_KEY_KP_DECIMAL         ,
    EMBER_KEY_KP_DIVIDE          ,
    EMBER_KEY_KP_MULTIPLY        ,
    EMBER_KEY_KP_SUBTRACT        ,
    EMBER_KEY_KP_ADD             ,
    EMBER_KEY_KP_ENTER           ,
    EMBER_KEY_KP_EQUAL           ,
    EMBER_KEY_LEFT_SHIFT         ,
    EMBER_KEY_LEFT_CONTROL       ,
    EMBER_KEY_LEFT_ALT           ,
    EMBER_KEY_LEFT_SUPER         ,
    EMBER_KEY_RIGHT_SHIFT        ,
    EMBER_KEY_RIGHT_CONTROL      ,
    EMBER_KEY_RIGHT_ALT          ,
    EMBER_KEY_RIGHT_SUPER        ,
    EMBER_KEY_MENU               ,
} emwin_key_code;

/**
 * @brief Code for identifying a mouse button.
 */
typedef enum emwin_mouse_code {
    EMBER_MOUSE_CODE_LEFT,
    EMBER_MOUSE_CODE_RIGHT,
    EMBER_MOUSE_CODE_MIDDLE,
} emwin_mouse_code;

/**
 * @brief Represents the directional state of a joystick hat (D-pad).
 *
 * Values may be combined using bitwise OR to represent diagonal directions.
 */
typedef enum emwin_hat_state {
    EMBER_HAT_STATE_CENTERED,       /**< No direction pressed. */
    EMBER_HAT_STATE_UP    = 1 << 0, /**< Up direction. */
    EMBER_HAT_STATE_RIGHT = 1 << 1, /**< Right direction. */
    EMBER_HAT_STATE_DOWN  = 1 << 2, /**< Down direction. */
    EMBER_HAT_STATE_LEFT  = 1 << 3  /**< Left direction. */
} emwin_hat_state;