#pragma once

#include "ember/core.h"

#include "ember/window/desktop.h"
#include "ember/window/window.h"
#include "ember/window/input.h"

/**
 * @brief Types of events generated by a desktop connection.
 *
 * Events are delivered through an event endpoint created with
 * emwin_desktop_open_events().
 */
typedef enum emwin_event_type {
    EMWIN_EVENT_MONITOR_CONNECT,           /**< New monitor was connected. */
    EMWIN_EVENT_MONITOR_DISCONNECT,        /**< Monitor has been disconnected. */
    EMWIN_EVENT_WINDOW_CLOSE,              /**< Window close was requested. */
    EMWIN_EVENT_WINDOW_RESIZE,             /**< Window client area size changed. */
    EMWIN_EVENT_WINDOW_FOCUS_GAINED,       /**< Window client area size changed. */
    EMWIN_EVENT_WINDOW_FOCUS_LOST,         /**< Window lost keyboard focus. */
    EMWIN_EVENT_INPUT_KEY_ACTION,          /**< Keyboard key was pressed or released. */
    EMWIN_EVENT_INPUT_MOUSE_MOTION,        /**< Mouse moved. */
    EMWIN_EVENT_INPUT_MOUSE_BUTTON_ACTION, /**< Mouse button was pressed or released. */
    EMWIN_EVENT_INPUT_MOUSE_WHEEL,         /**< Mouse wheel was scrolled. */
    EMWIN_EVENT_JOYSTICK_CONNECT,          /**< Joystick was connected. */
    EMWIN_EVENT_JOYSTICK_DISCONNECT,       /**< Joystick was disconnected. */
} emwin_event_type; 

/**
 * @brief Event generated by a desktop connection.
 *
 * The data stored in the event union is determined by @ref type.
 */
typedef struct emwin_desktop_event {
    /** @brief Type of event contained in this structure. */
    emwin_event_type type;

    /**
     * @brief Event-specific data.
     *
     * Only the member corresponding to @ref type is valid.
     */
    union {
        /**
         * @brief Data for EMWIN_EVENT_WINDOW_CLOSE.
         *
         * Contains the identifier of the window that requested closing.
         */
        struct {
            /** @brief Window identifier. */
            emwin_window_id id;
        } window_close;

        /**
         * @brief Data for EMWIN_EVENT_MONITOR_CONNECT.
         *
         * Contains the identifier of the monitor that has been connected.
         */
        struct {
            emwin_monitor monitor;
        } monitor_connect;

        /**
         * @brief Data for EMWIN_EVENT_MONITOR_DISCONNECT.
         *
         * Contains the identifier of the monitor that has been disconnected.
         */
        struct {
            emwin_monitor monitor;
        } monitor_disconnect;

        /**
         * @brief Data for EMWIN_EVENT_WINDOW_RESIZE.
         *
         * Contains the new window dimensions.
         */
        struct {
            /** @brief New window size in pixels. */
            uvec2 size;
        } window_resize;

        /**
         * @brief Data for EMWIN_EVENT_WINDOW_FOCUS_GAINED.
         *
         * Indicates the window received input focus.
         */
        struct {
            /** @brief Window identifier. */
            emwin_window_id id;
        } window_focus_gained;

        /**
         * @brief Data for EMWIN_EVENT_WINDOW_FOCUS_LOST.
         *
         * Indicates the window lost input focus.
         */
        struct {
            /** @brief Window identifier. */
            emwin_window_id id;
        } window_focus_lost;

        /**
         * @brief Data for EMWIN_EVENT_INPUT_KEY_ACTION.
         *
         * Represents a keyboard key press or release.
         */
        struct {
            /** @brief Window identifier. */
            emwin_window_id id;

            /** @brief Key code. */
            emwin_key_code key;

            /** @brief True if pressed, false if released. */
            b8 pressed;
        } input_key_action;

        /**
         * @brief Data for EMWIN_EVENT_INPUT_MOUSE_MOTION.
         *
         * Contains relative mouse movement.
         */
        struct {
            /** @brief Window identifier. */
            emwin_window_id id;

            /** @brief Mouse movement delta. */
            uvec2 delta_pos;
        } mouse_motion;

        /**
         * @brief Data for EMWIN_EVENT_INPUT_MOUSE_BUTTON_ACTION.
         *
         * Represents a mouse button press or release.
         */
        struct {
            /** @brief Window identifier. */
            emwin_window_id id;

            /** @brief Mouse button code. */
            emwin_mouse_code button;

            /** True if pressed, false if released. */
            b8 pressed;
        } button_action;

        /**
         * @brief Data for EMWIN_EVENT_INPUT_MOUSE_WHEEL.
         *
         * Contains scroll movement.
         */
        struct {
            /** @brief Window identifier. */
            emwin_window_id id;

            /** @brief Scroll delta. */
            vec2 delta_scroll;
        } mouse_wheel;

        /**
         * @brief Data for EMWIN_EVENT_JOYSTICK_CONNECT.
         *
         * Indicates a joystick became available.
         */
        struct {
            /** @brief Connected joystick identifier. */
            emwin_joystick_id id;
        } joystick_connect;

        /**
         * @brief Data for EMWIN_EVENT_JOYSTICK_DISCONNECT.
         *
         * Indicates a joystick was removed.
         */
        struct {
            /** @brief Disconnected joystick identifier. */
            emwin_joystick_id id;
        } joystick_disconnect;
    };
} emwin_desktop_event;
