#pragma once

#include "ember/core.h"

/**
 * @brief Describes a data format used by the ember_window subsystem.
 * Any other format values outside this enum is not supported by 
 * the subsystem.
 *
 * Used for shm software rendering, window icons and custom cursors.
 */
typedef u32 emwin_format;

#define EMWIN_FORMAT_UNDEFINED 0

/**
 * @brief BGR formats
 */
#define EMWIN_FORMAT_BGR8_UNORM  EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGR8_SNORM  EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 3, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGR8_UINT   EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGR8_SINT   EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 3, EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGR8_SRGB   EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 3, EMBER_FORMAT_FLAG_SRGB | EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGRA8_UNORM EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGRA8_SNORM EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 4, EMBER_FORMAT_FLAG_NORMALIZED | EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGRA8_UINT  EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGRA8_SINT  EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_SINT, 8, 4, EMBER_FORMAT_FLAG_BGRA)
#define EMWIN_FORMAT_BGRA8_SRGB  EMBER_FORMAT_MAKE(EMBER_DATA_TYPE_UINT, 8, 4, EMBER_FORMAT_FLAG_SRGB | EMBER_FORMAT_FLAG_BGRA)

